In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Puerto Ayora,EC,2020-10-31 17:10:15,-0.74,-90.35,75.20,73,75,17.22
1,1,Rikitea,PF,2020-10-31 17:07:31,-23.12,-134.97,74.95,71,7,7.65
2,2,Lorengau,PG,2020-10-31 17:10:18,-2.02,147.27,80.83,76,15,4.92
3,3,Kendari,ID,2020-10-31 17:11:21,-3.94,122.50,75.69,91,96,3.83
4,4,Mar Del Plata,AR,2020-10-31 17:11:19,-38.00,-57.56,71.60,37,0,8.05

In [3]:
#get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key = g_key)

In [5]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

In [7]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [19]:
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [57]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df_null_row = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df = preferred_cities_df_null_row.dropna()

In [58]:
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Puerto Ayora,EC,2020-10-31 17:10:15,-0.74,-90.35,75.20,73,75,17.22
2,2,Lorengau,PG,2020-10-31 17:10:18,-2.02,147.27,80.83,76,15,4.92
3,3,Kendari,ID,2020-10-31 17:11:21,-3.94,122.50,75.69,91,96,3.83
11,11,Ovalle,CL,2020-10-31 17:07:48,-30.60,-71.20,81.41,26,0,9.98
12,12,Sao Filipe,CV,2020-10-31 17:10:22,14.90,-24.50,82.08,61,57,15.93
13,13,Bubaque,GW,2020-10-31 17:11:59,11.28,-15.83,85.73,60,65,6.08
14,14,San Policarpo,PH,2020-10-31 17:11:26,12.18,125.51,81.36,80,100,17.40
18,18,Talaga,PH,2020-10-31 17:12:00,15.39,120.59,78.80,74,75,4.70
20,20,Bathsheba,BB,2020-10-31 17:12:00,13.22,-59.52,84.20,79,75,14.99
21,21,Atuona,PF,2020-10-31 17:10:17,-9.80,-139.03,78.17,76,17,17.83

In [59]:
preferred_cities_df.count()

City_ID       176
City          176
Country       176
Date          176
Lat           176
Lng           176
Max Temp      176
Humidity      176
Cloudiness    176
Wind Speed    176
dtype: int64

In [60]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp    Lat     Lng Hotel Name
0    Puerto Ayora      EC     75.20  -0.74  -90.35
2        Lorengau      PG     80.83  -2.02  147.27
3         Kendari      ID     75.69  -3.94  122.50
11         Ovalle      CL     81.41 -30.60  -71.20
12     Sao Filipe      CV     82.08  14.90  -24.50
13        Bubaque      GW     85.73  11.28  -15.83
14  San Policarpo      PH     81.36  12.18  125.51
18         Talaga      PH     78.80  15.39  120.59
20      Bathsheba      BB     84.20  13.22  -59.52
21         Atuona      PF     78.17  -9.80 -139.03

In [61]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [66]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [68]:
hotel_df.head(10)

             City Country  Max Temp    Lat     Lng                  Hotel Name
0    Puerto Ayora      EC     75.20  -0.74  -90.35   Finch Bay Galapagos Hotel
2        Lorengau      PG     80.83  -2.02  147.27  Lorengau Harbourside Hotel
3         Kendari      ID     75.69  -3.94  122.50                 Hotel Wixel
11         Ovalle      CL     81.41 -30.60  -71.20        Hotel Altos de Tuqui
12     Sao Filipe      CV     82.08  14.90  -24.50                 Tortuga B&B
13        Bubaque      GW     85.73  11.28  -15.83          Casa Dora, Bubaque
14  San Policarpo      PH     81.36  12.18  125.51        Zal-Ann Beach Resort
18         Talaga      PH     78.80  15.39  120.59        The Farmhouse By EDL
20      Bathsheba      BB     84.20  13.22  -59.52              Atlantis Hotel
21         Atuona      PF     78.17  -9.80 -139.03                 Villa Enata

In [72]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [73]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))